[project] 
name = "spark_custom_io"
version = "0.1.0"
description = "Custom PySpark DataSource for Databricks"
requires-python = ">=3.8"
dependencies = [
    "pyspark>=4.0.0",
]
authors = [
    { name = "de.lopezbarron@gmail.com" }
]
